### ISSUE TITLE
Does the default parameters work? 

### ISSUE THREAD

**Issue by JonasRSV** [Jason-CKY/lunar_lander_DQN#1]
When I run your main.py it crashes around episode 200 with

```bash
Episode 185/500 | Reward -480.19172828081116
 37%|███████████████████████████████████████████████████████████████████████████████▉                                                                                                                                        | 185/500 [01:25<02:27,  2.13it/s]/home/jonas/Notes/2020/RL/lab2/problem1/lunar_lander_DQN/Agents/q_agent.py:243: RuntimeWarning: invalid value encountered in true_divide
  action_probs = exp_preferences / reshaped_sum_of_exp_preferences
Traceback (most recent call last):
  File "main.py", line 154, in <module>
    main()
  File "main.py", line 151, in main
    run_experiment(current_env, current_agent, environment_parameters, agent_parameters, experiment_parameters)
  File "main.py", line 81, in run_experiment
    rl_glue.rl_episode(experiment_parameters["timeout"])
  File "/home/jonas/Notes/2020/RL/lab2/problem1/lunar_lander_DQN/rl_glue.py", line 185, in rl_episode
    rl_step_result = self.rl_step()
  File "/home/jonas/Notes/2020/RL/lab2/problem1/lunar_lander_DQN/rl_glue.py", line 135, in rl_step
    self.last_action = self.agent.agent_step(reward, last_state)
  File "/home/jonas/Notes/2020/RL/lab2/problem1/lunar_lander_DQN/Agents/q_agent.py", line 152, in agent_step
    action = self.policy(state)
  File "/home/jonas/Notes/2020/RL/lab2/problem1/lunar_lander_DQN/Agents/q_agent.py", line 117, in policy
    action = self.rand_generator.choice(self.num_actions, p=probs_batch.squeeze())
  File "mtrand.pyx", line 922, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN
 37%|███████████████████████████████████████████████████████████████████████████████▉                                                                                                                                        | 185/500 [01:25<02:25,  2.16it/s]
/home/jonas/.local/lib/python3.6/site-packages/matplotlib/backends/backend_gtk3.py:197: Warning: Source ID 8 was not found when attempting to remove it
  GLib.source_remove(self._idle_draw_id)
```

Was the parameters in main.py the ones you used when you solved the environment? :)

**Comment by Jason-CKY** [comment]
The parameters in main.py is the same as the one in the README, which is the one i used to solve the environment. It seems that the softmax function has calculated NaN values somewhere within the function. You could try replacing the custom Softmax function with the pytorch's nn.Softmax. It should resolve this issue.

**Comment by JonasRSV** [comment]
Thanks! it did
