### ISSUE TITLE
After some episodes, it reports ValueError: probabilities contain NaN, how to fix this?

### ISSUE THREAD

**Issue by Matten95** [Jason-CKY/lunar_lander_DQN#2]
Traceback (most recent call last):
  File "main.py", line 154, in <module>
    main()
  File "main.py", line 151, in main
    run_experiment(current_env, current_agent, environment_parameters, agent_parameters, experiment_parameters)
  File "main.py", line 81, in run_experiment
    rl_glue.rl_episode(experiment_parameters["timeout"])
  File "/Users/Matt/lunar_lander_DQN/rl_glue.py", line 185, in rl_episode
    rl_step_result = self.rl_step()
  File "/Users/Matt/lunar_lander_DQN/rl_glue.py", line 135, in rl_step
    self.last_action = self.agent.agent_step(reward, last_state)
  File "/Users/Matt/lunar_lander_DQN/Agents/q_agent.py", line 152, in agent_step
    action = self.policy(state)
  File "/Users/Matt/lunar_lander_DQN/Agents/q_agent.py", line 117, in policy
    action = self.rand_generator.choice(self.num_actions, p=probs_batch.squeeze())
  File "mtrand.pyx", line 928, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN

**Comment by Jason-CKY** [comment]
Please refer to the previous issue #1. 
As this is my first project for RL, the code is not quite up to standard. I will refactor the codebase and resolve this issue in the upcoming commit. Meanwhile, follow the fix given in #1.
